### ISSUE TITLE
Compilation error: name 'raw' is defined multiple times

### ISSUE THREAD

**Issue by leecbaker** [blas-lapack-rs/blas-src#13]
Compiling on Mac, I see the following error:

```
   Compiling blas-src v0.8.0
error[E0259]: the name `raw` is defined multiple times
  --> /Users/lee/.cargo/registry/src/github.com-1ecc6299db9ec823/blas-src-0.8.0/src/lib.rs:50:1
   |
38 | extern crate accelerate_src as raw;
   | ----------------------------------- previous import of the extern crate `raw` here
...
50 | extern crate openblas_src as raw;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `raw` reimported here
   |
   = note: `raw` must be defined only once in the type namespace of this module
help: you can use `as` to change the binding name of the import
   |
50 | extern crate openblas_src as other_raw;
   |

For more information about this error, try `rustc --explain E0259`.
error: could not compile `blas-src` due to previous error
```

Any ideas how to fix this?

The library is compiled in a Cargo.toml that includes the following:

```toml
# For BLAS, use the native libraries on Mac
[target.'cfg(target_os = "macos")'.dependencies]
blas-src = { version = "0.8", features = ["accelerate"] }

# For other platforms, use openblas, which we will probably have to manually install
[target.'cfg(any(target_os = "windows", target_os = "linux"))'.dependencies]
blas-src = { version = "0.8", features = ["openblas"] }
openblas-src = { version = "*", features = ["system"]}
```
