### ISSUE TITLE
Export features in `*-src` crates in `blas-src`

### ISSUE THREAD

**Issue by 2pt0** [blas-lapack-rs/blas-src#25]
`openblas-src` and `netlib-src` (and potentially others) have features that are not accessible from this crate (e.g. `static` for static linking and `system` for using a system-local install). Can these features be exported in `blas-src`?

An example implementation may be

```toml
# Cargo.toml

[features]
static = ["openblas-src?/static", "netlib-src?/static"]
# Other features
```

I think disabling LAPACK builds by default for supported BLAS implementations is also desirable, i.e. don't build LAPACK code in OpenBLAS from `blas-src`.
